CREATE TABLE Minions (
	Id INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Age INT NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE Towns (
	Id INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	PRIMARY KEY (Id)
);

ALTER TABLE Minions 
ADD TownsId INT;

TRUNCATE TABLE Minions;

DROP TABLE Minions;
DROP TABLE Towns;

CREATE TABLE People (
	Id INT NOT NULL PRIMARY KEY,
	Name VARCHAR(200) NOT NULL,
	Picture INT,
	Height DECIMAL(18, 2),
	Weight DECIMAL(18, 2),
	Gender BIT NOT NULL,
	Birthdate DATE NOT NULL,
	Biography VARCHAR(MAX),
);

CREATE TABLE Users (
	Id BIGINT NOT NULL,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(26) NOT NULL,
	ProfilePicture INT,
	LastLogTime DATETIME,
	IsDeleted BIT,
);

ALTER TABLE Users
ADD CONSTRAINT PK_IdAndUsername PRIMARY KEY (Id, Username);

ALTER TABLE Users
ADD CHECK(LEN(Password) >= 5)

ALTER TABLE Users
ADD CONSTRAINT DF_LastLongTime DEFAULT GETDATE() FOR LastLogTime

ALTER TABLE Users
DROP CONSTRAINT PK_IdAndUsername

ALTER TABLE USERS
ADD CONSTRAINT PK_Id PRIMARY KEY(Id)

ALTER TABLE Users
ADD CONSTRAINT UsernameShouldBe3CharsLong CHECK (LEN(Username) >= 3);